"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type PageKey = "overview" | "intent" | "api" | "refusal" | "conversations";
type Conversation = { id:string; botId:string; botName:string; sessionId:string; userMessage:string; botReply:string; createdAt:number; intent:string; refused:boolean; refusalReason:string|null; model:string|null; inputTokens:number|null; outputTokens:number|null; latencyMs:number|null; costUsd:number|null; toolName:string|null };
type ConversationSession = { key:string; sessionId:string; botName:string; messages:Conversation[]; startedAt:number; lastAt:number; primaryIntent:string; hasRefusal:boolean };
type Data = { mode?:"mock"; planUsage:{monthKey:string;used:number;limit:number;percent:number;warningLevel:"none"|"notice"|"warning"|"blocked"}|null; bots:{id:string;name:string}[]; coverage:{logs:number;api:number;latency:number;tokens:number;tools:number}; summary:{messages:number;conversations:number;activeSessions:number;responseRate:number|null;refusalRate:number|null;apiSuccessRate:number|null;averageLatencyMs:number|null;inputTokens:number;outputTokens:number;estimatedCostUsd:number|null}; daily:{date:string;messages:number;conversations:number;refusals:number}[]; intents:{name:string;count:number;share:number}[]; refusalReasons:{name:string;count:number;share:number}[]; refusedConversations:Conversation[]; tools:{name:string;calls:number;successRate:number|null;averageLatencyMs:number|null}[]; conversations:Conversation[] };

const tabs:{key:PageKey;label:string;icon:string}[]=[{key:"overview",label:"개요",icon:"◫"},{key:"intent",label:"의도 분석",icon:"⌁"},{key:"api",label:"API / 도구 분석",icon:"⌘"},{key:"refusal",label:"거절 분석",icon:"⊘"},{key:"conversations",label:"대화 탐색",icon:"▤"}];
const meta:Record<PageKey,[string,string]>={overview:["개요","실제 고객 대화에서 수집된 운영 지표입니다."],intent:["의도 분석","고객 메시지에서 분류한 실제 문의 유형입니다."],api:["API / 도구 분석","새 대화부터 수집되는 모델과 도구 실행 성능입니다."],refusal:["거절 분석","답변 불가 표현과 모델 거절 응답을 분석합니다."],conversations:["대화 탐색","저장된 고객 질문과 챗봇 답변을 확인하세요."]};
const nf=new Intl.NumberFormat("ko-KR");
const percent=(v:number|null)=>v===null?"측정 전":`${v.toFixed(1)}%`;
const duration=(v:number|null)=>v===null?"측정 전":v>=1000?`${(v/1000).toFixed(1)}초`:`${v}ms`;
const dollars=(v:number|null)=>v===null?"측정 전":`$${v>=1?v.toFixed(2):v.toFixed(4)}`;

function Head({title,sub}:{title:string;sub:string}){return <div className="analytics-section-head"><div><h3>{title}</h3><p>{sub}</p></div></div>}
function Empty({text}:{text:string}){return <div className="analytics-empty"><span>⌁</span><strong>아직 표시할 데이터가 없어요</strong><p>{text}</p></div>}
function Kpi({label,value,note,signal=false,measured=true}:{label:string;value:string;note:string;signal?:boolean;measured?:boolean}){return <div className="analytics-card analytics-kpi"><span>{label}</span><strong className={measured?"":"analytics-unmeasured"}>{value}</strong><small>{note}</small>{signal&&<i className="analytics-signal"/>}</div>}
function Summary({label,note,value}:{label:string;note:string;value:string}){return <div className="analytics-summary-row"><div><span>{label}</span><small>{note}</small></div><strong>{value}</strong></div>}

function Chart({data,value="messages"}:{data:Data["daily"];value?:"messages"|"conversations"|"refusals"}){const values=data.map(d=>d[value]);const max=Math.max(...values,1);const points=values.map((v,i)=>`${values.length<2?0:(i/(values.length-1))*760},${195-(v/max)*165}`).join(" ");const area=points?`M${points.replaceAll(" "," L")} L760,220 L0,220 Z`:"";const labels=data.length?[data[0],data[Math.floor(data.length/2)],data[data.length-1]]:[];return <div className="analytics-chart"><svg viewBox="0 0 760 220" preserveAspectRatio="none"><defs><linearGradient id={`real-${value}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7163e9" stopOpacity=".22"/><stop offset="1" stopColor="#7163e9" stopOpacity="0"/></linearGradient></defs><path d="M0 195H760M0 140H760M0 85H760M0 30H760" stroke="#edf0f5"/>{area&&<path d={area} fill={`url(#real-${value})`}/>}<polyline points={points} fill="none" stroke="#6958e9" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="analytics-chart-labels">{labels.map(d=><span key={d.date}>{new Date(`${d.date}T00:00:00`).toLocaleDateString("ko-KR",{month:"short",day:"numeric"})}</span>)}</div></div>}

function IntentTable({items}:{items:Data["intents"]}){if(!items.length)return <Empty text="챗봇에서 대화를 생성하면 문의 의도가 자동으로 분류됩니다."/>;return <table className="analytics-table"><thead><tr><th>문의 의도</th><th>메시지</th><th>비율</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.name}><td><b className="intent-name"><i>{["◒","⌁","◈","◌","△","◇","○"][i]??"○"}</i>{x.name}</b></td><td className="analytics-mono">{nf.format(x.count)}</td><td className="analytics-trend">{x.share.toFixed(1)}%</td></tr>)}</tbody></table>}

function Overview({d}:{d:Data}){const s=d.summary;return <><div className="analytics-kpi-grid"><Kpi label="전체 대화" value={nf.format(s.conversations)} note={`${nf.format(s.messages)}개 메시지`}/><Kpi label="활성 세션" value={nf.format(s.activeSessions)} note="고유 세션 ID 기준"/><Kpi label="응답 완료율" value={percent(s.responseRate)} note="거절 응답 제외" signal/><Kpi label="거절률" value={percent(s.refusalRate)} note={`${d.refusalReasons.reduce((a,b)=>a+b.count,0)}건 감지`}/><Kpi label="API 성공률" value={percent(s.apiSuccessRate)} note={`${d.coverage.api}건 실측`} measured={s.apiSuccessRate!==null}/><Kpi label="측정 비용" value={dollars(s.estimatedCostUsd)} note={`${d.coverage.tokens}건 토큰 측정`} measured={s.estimatedCostUsd!==null}/></div><div className="analytics-grid-two"><div className="analytics-card analytics-section-card"><Head title="대화량 추이" sub="선택 기간의 일별 실제 메시지 수"/><Chart data={d.daily}/></div><div className="analytics-card analytics-section-card"><Head title="문의 의도 TOP 5" sub="고객 질문에서 자동 분류"/><IntentTable items={d.intents.slice(0,5)}/></div></div><div className="analytics-grid-two analytics-spaced"><div className="analytics-card analytics-summary"><Head title="실측 사용량" sub="OpenAI 응답 usage로 수집"/><Summary label="입력 토큰" note={`${d.coverage.tokens}건 측정`} value={nf.format(s.inputTokens)}/><Summary label="출력 토큰" note="Chat Completions 기준" value={nf.format(s.outputTokens)}/><Summary label="평균 응답 시간" note={`${d.coverage.latency}건 측정`} value={duration(s.averageLatencyMs)}/></div><div className="analytics-card analytics-summary"><Head title="데이터 수집 상태" sub={d.mode==="mock"?"실제 DB에 저장되지 않는 데모 데이터":"목업 없이 실제 로그만 표시"}/><Summary label="분석 대상 로그" note="선택 기간 및 챗봇 기준" value={`${nf.format(d.coverage.logs)}건`}/><Summary label="API 계측 로그" note="계측 기능 적용 이후" value={`${nf.format(d.coverage.api)}건`}/><Summary label="도구 사용 로그" note="Q&A 및 문서 검색" value={`${nf.format(d.coverage.tools)}건`}/></div></div></>}

function IntentPage({d}:{d:Data}){const top=d.intents[0];return <><div className="analytics-hero"><div><small>실제 메시지 분류</small><h2>{top?`${top.name} 문의가 가장 많아요`:"분류할 대화가 없어요"}</h2><p>{top?`전체 메시지의 ${top.share.toFixed(1)}%를 차지합니다.`:"대화를 생성하면 자동으로 분석됩니다."}</p></div><strong>{top?nf.format(top.count):"0"}<small>메시지</small></strong></div><div className="analytics-grid-two"><div className="analytics-card analytics-section-card"><Head title="의도별 비중" sub="실제 고객 메시지 기준"/>{d.intents.length?d.intents.slice(0,7).map(x=><div className="analytics-bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.max(x.share,2)}%`}}/></div><b>{x.share.toFixed(1)}%</b></div>):<Empty text="분석 가능한 대화가 없습니다."/>}</div><div className="analytics-card analytics-section-card"><Head title="전체 의도" sub="건수와 비율"/><IntentTable items={d.intents}/></div></div></>}

function ApiPage({d}:{d:Data}){const s=d.summary;return <><div className="analytics-metric-grid"><Kpi label="계측된 API 요청" value={nf.format(d.coverage.api)} note="기능 적용 이후"/><Kpi label="API 성공률" value={percent(s.apiSuccessRate)} note="실제 요청 결과" measured={s.apiSuccessRate!==null}/><Kpi label="평균 응답 시간" value={duration(s.averageLatencyMs)} note={`${d.coverage.latency}건 측정`} measured={s.averageLatencyMs!==null}/><Kpi label="도구 실행" value={nf.format(d.coverage.tools)} note="Q&A / RAG 검색"/></div><div className="analytics-grid-two"><div className="analytics-card analytics-section-card"><Head title="채팅 요청 추이" sub="저장된 실제 요청"/><Chart data={d.daily}/></div><div className="analytics-card analytics-section-card"><Head title="도구 성능" sub="실제 실행된 검색 도구"/>{d.tools.length?<table className="analytics-table"><thead><tr><th>도구</th><th>호출</th><th>성공률</th><th>평균 시간</th></tr></thead><tbody>{d.tools.map(t=><tr key={t.name}><td><b>{t.name}</b></td><td>{t.calls}</td><td>{percent(t.successRate)}</td><td>{duration(t.averageLatencyMs)}</td></tr>)}</tbody></table>:<Empty text="새로운 Q&A 또는 문서 기반 대화부터 기록됩니다."/>}</div></div></>}

function RefusalPage({d}:{d:Data}){
  const total=d.refusalReasons.reduce((a,b)=>a+b.count,0);
  const refusals=d.refusedConversations??[];
  const needsDocs=(item:Conversation)=>!/안전 정책|기밀|민감정보/.test(item.refusalReason??"");
  return <>
    <div className="analytics-hero"><div><small>실제 답변 분석</small><h2>{total?`${total}건의 거절 응답을 감지했어요`:"감지된 거절 응답이 없어요"}</h2><p>어떤 질문이 거절됐는지 확인하고 필요한 문서와 답변 정책을 보강하세요.</p></div><strong>{percent(d.summary.refusalRate)}<small>전체 메시지 대비</small></strong></div>
    <div className="analytics-grid-two"><div className="analytics-card analytics-section-card"><Head title="거절 추이" sub="일별 감지 건수"/><Chart data={d.daily} value="refusals"/></div><div className="analytics-card analytics-section-card"><Head title="거절 사유" sub="실제 답변에서 감지된 유형"/>{d.refusalReasons.length?d.refusalReasons.map(x=><div className="analytics-bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.max(x.share,2)}%`}}/></div><b>{x.count}건</b></div>):<Empty text="선택 기간에 감지된 거절이 없습니다."/>}</div></div>
    <div className="analytics-card analytics-refusal-list"><Head title="거절된 질문과 개선 제안" sub="최근 거절 질문을 확인하고 해당 챗봇의 지식 문서 또는 답변 정책을 보강하세요."/>{refusals.length?<table className="analytics-table analytics-refusal-table"><thead><tr><th>고객 질문</th><th>챗봇</th><th>거절 사유</th><th>개선 제안</th><th/></tr></thead><tbody>{refusals.map(item=>{const addDocs=needsDocs(item);return <tr key={item.id}><td><b>{item.userMessage}</b><small>{new Date(item.createdAt*1000).toLocaleString("ko-KR")}</small></td><td>{item.botName}</td><td><span className="analytics-pill red">{item.refusalReason??"답변 불가"}</span></td><td><strong className="analytics-suggestion-title">{addDocs?`‘${item.intent}’ 관련 문서를 추가해보세요.`:"문서보다 답변 정책을 먼저 확인하세요."}</strong><small>{addDocs?"제품 자료, 정책, FAQ 등 답변의 근거가 되는 내용을 등록하면 유사 질문의 거절을 줄일 수 있습니다.":"기밀·민감정보 또는 안전 정책에 해당하는 질문은 시스템 프롬프트와 허용 범위를 검토해야 합니다."}</small></td><td><a className="analytics-action-link" href={addDocs?`/bots/${item.botId}/docs`:`/bots/${item.botId}`}>{addDocs?"문서 추가":"설정 확인"} →</a></td></tr>})}</tbody></table>:<Empty text="선택 기간에 감지된 거절 질문이 없습니다."/>}</div>
  </>
}

function LegacyConversations({d}:{d:Data}){const[q,setQ]=useState("");const[selected,setSelected]=useState<Conversation|null>(null);const rows=useMemo(()=>d.conversations.filter(x=>`${x.userMessage} ${x.botReply} ${x.intent} ${x.botName}`.toLowerCase().includes(q.toLowerCase())),[d,q]);return <><div className="analytics-card analytics-table-card"><Head title="실제 대화 로그" sub={`최근 ${d.conversations.length}개 메시지`}/><div className="analytics-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕  질문, 답변, 의도 검색..."/></div>{rows.length?<table className="analytics-table analytics-conversation-table"><thead><tr><th>세션</th><th>고객 질문</th><th>의도</th><th>챗봇</th><th>시간</th><th>상태</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>setSelected(x)}><td className="analytics-mono">{x.sessionId==="legacy"?"이전 로그":x.sessionId.slice(0,8)}</td><td className="analytics-message-cell">{x.userMessage}</td><td>{x.intent}</td><td>{x.botName}</td><td className="analytics-mono">{new Date(x.createdAt*1000).toLocaleString("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</td><td><span className={`analytics-pill ${x.refused?"red":""}`}>{x.refused?"거절 감지":"응답 완료"}</span></td></tr>)}</tbody></table>:<Empty text="검색 조건에 맞는 대화가 없습니다."/>}</div>{selected&&<div className="analytics-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="analytics-drawer" onClick={e=>e.stopPropagation()}><button className="analytics-close" onClick={()=>setSelected(null)}>×</button><small>대화 상세</small><h2>{selected.intent}</h2><div className="analytics-drawer-tags"><span>{selected.botName}</span><span>{selected.refused?"거절 감지":"응답 완료"}</span></div><div className="analytics-chat"><p>{selected.userMessage}<small>고객 · {new Date(selected.createdAt*1000).toLocaleString("ko-KR")}</small></p><p className="agent">{selected.botReply}<small>AI 챗봇</small></p></div></aside></div>}</>}

function groupConversationSessions(messages:Conversation[]):ConversationSession[]{
  const groups=new Map<string,Conversation[]>();
  for(const message of messages){
    const key=message.sessionId==="legacy"?`${message.botId}:legacy:${message.id}`:`${message.botId}:${message.sessionId}`;
    groups.set(key,[...(groups.get(key)??[]),message]);
  }
  return [...groups.entries()].map(([key,items])=>{
    const sorted=[...items].sort((a,b)=>a.createdAt-b.createdAt);
    const intents=new Map<string,number>();
    for(const item of sorted)intents.set(item.intent,(intents.get(item.intent)??0)+1);
    const primaryIntent=[...intents.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??"기타 문의";
    return {key,sessionId:sorted[0].sessionId,botName:sorted[0].botName,messages:sorted,startedAt:sorted[0].createdAt,lastAt:sorted[sorted.length-1].createdAt,primaryIntent,hasRefusal:sorted.some(item=>item.refused)};
  }).sort((a,b)=>b.lastAt-a.lastAt);
}

function Conversations({d}:{d:Data}){
  const[q,setQ]=useState("");
  const[selected,setSelected]=useState<ConversationSession|null>(null);
  const sessions=useMemo(()=>groupConversationSessions(d.conversations),[d.conversations]);
  const rows=useMemo(()=>sessions.filter(session=>session.messages.some(message=>`${message.userMessage} ${message.botReply} ${message.intent} ${message.botName}`.toLowerCase().includes(q.toLowerCase()))),[sessions,q]);
  const totalTokens=(session:ConversationSession)=>session.messages.reduce((sum,message)=>sum+(message.inputTokens??0)+(message.outputTokens??0),0);
  const measuredLatency=(session:ConversationSession)=>session.messages.filter(message=>message.latencyMs!==null).map(message=>message.latencyMs as number);
  const totalCost=(session:ConversationSession)=>session.messages.some(message=>message.costUsd!==null)?session.messages.reduce((sum,message)=>sum+(message.costUsd??0),0):null;
  return <><div className="analytics-card analytics-table-card"><Head title="대화 세션" sub={`${sessions.length}개 세션 · ${d.conversations.length}개 메시지`}/><div className="analytics-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕  세션의 질문, 답변, 의도 검색..."/></div>{rows.length?<table className="analytics-table analytics-conversation-table"><thead><tr><th>세션</th><th>첫 질문</th><th>대화 턴</th><th>주요 의도</th><th>챗봇</th><th>최근 활동</th><th>상태</th></tr></thead><tbody>{rows.map(session=><tr key={session.key} onClick={()=>setSelected(session)}><td className="analytics-mono">{session.sessionId==="legacy"?"이전 로그":session.sessionId.slice(0,8)}</td><td className="analytics-message-cell">{session.messages[0].userMessage}</td><td><span className="analytics-session-count">{session.messages.length}턴</span></td><td>{session.primaryIntent}</td><td>{session.botName}</td><td className="analytics-mono">{new Date(session.lastAt*1000).toLocaleString("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</td><td><span className={`analytics-pill ${session.hasRefusal?"red":""}`}>{session.hasRefusal?"거절 포함":"응답 완료"}</span></td></tr>)}</tbody></table>:<Empty text="검색 조건에 맞는 대화 세션이 없습니다."/>}</div>{selected&&<div className="analytics-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="analytics-drawer analytics-session-drawer" onClick={e=>e.stopPropagation()}><button className="analytics-close" onClick={()=>setSelected(null)}>×</button><small>대화 세션 상세</small><h2>{selected.sessionId==="legacy"?"이전 대화":`세션 ${selected.sessionId.slice(0,8)}`}</h2><div className="analytics-drawer-tags"><span>{selected.botName}</span><span>{selected.messages.length}턴</span><span>{selected.primaryIntent}</span></div><div className="analytics-chat">{selected.messages.map((message,index)=><div className="analytics-turn" key={message.id}><p>{message.userMessage}<small>고객 · {new Date(message.createdAt*1000).toLocaleString("ko-KR")}</small></p><p className="agent">{message.botReply}<small>AI 챗봇 · {index+1}번째 응답</small></p></div>)}</div><div className="analytics-insight"><b>세션 실측 정보</b><div><span>주요 문의 의도</span><strong>{selected.primaryIntent}</strong></div><div><span>대화 턴</span><strong>{selected.messages.length}회</strong></div><div><span>거절 응답</span><strong>{selected.messages.filter(message=>message.refused).length}건</strong></div><div><span>전체 토큰</span><strong>{selected.messages.some(message=>message.inputTokens!==null)?nf.format(totalTokens(selected)):"측정 전"}</strong></div><div><span>평균 응답 시간</span><strong>{measuredLatency(selected).length?duration(Math.round(measuredLatency(selected).reduce((a,b)=>a+b,0)/measuredLatency(selected).length)):"측정 전"}</strong></div><div><span>예상 비용</span><strong>{dollars(totalCost(selected))}</strong></div></div></aside></div>}</>;
}

void LegacyConversations;

export default function LiveAnalyticsDashboard(){const[page,setPage]=useState<PageKey>("overview");const[days,setDays]=useState(30);const[botId,setBotId]=useState("all");const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{const mock=typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("mock")==="1";const r=await fetch(`/api/analytics?days=${days}&botId=${encodeURIComponent(botId)}&mock=${mock?"1":"0"}`,{cache:"no-store"});if(!r.ok)throw new Error("분석 데이터를 불러오지 못했습니다.");setData(await r.json())}catch(e){setError(e instanceof Error?e.message:"오류가 발생했습니다.")}finally{setLoading(false)}},[days,botId]);useEffect(()=>{void load()},[load]);function exportData(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ideal-ai-analytics-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}const selectedBot=botId==="all"?"전체 챗봇":data?.bots.find(bot=>bot.id===botId)?.name??"선택한 챗봇";const mock=data?.mode==="mock";return <div className="analytics-app"><header className="analytics-topbar"><div><span>IDEAL AI</span><b>/</b><strong>{meta[page][0]}</strong><em className="analytics-current-bot">{selectedBot}</em></div><div><button onClick={()=>void load()}>↻</button><button>?</button></div></header><main className="analytics-main"><div className="analytics-page-heading"><div><small><i/>{mock?"스크린샷용 데모 데이터":"실제 서버 데이터"}</small><h1>{meta[page][0]}</h1><p>{mock?"제조기업 고객지원 운영 흐름을 재현한 데모 지표입니다.":meta[page][1]}</p></div><div className="analytics-filters"><label><span>기간</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>최근 7일</option><option value={30}>최근 30일</option><option value={90}>최근 90일</option></select></label><label><span>챗봇</span><select value={botId} onChange={e=>setBotId(e.target.value)}><option value="all">전체 챗봇</option>{data?.bots.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><button className="dark" onClick={exportData}>내보내기 ↗</button></div></div><nav className="analytics-tabs">{tabs.map(x=><button className={page===x.key?"active":""} onClick={()=>setPage(x.key)} key={x.key}><i>{x.icon}</i>{x.label}</button>)}</nav>{loading?<div className="analytics-loading"><i/><p>{selectedBot} 데이터를 집계하고 있어요</p></div>:error?<div className="analytics-error"><strong>데이터를 불러오지 못했어요</strong><p>{error}</p><button onClick={()=>void load()}>다시 시도</button></div>:data&&data.coverage.logs===0?<Empty text="선택한 기간과 챗봇에 저장된 대화가 없습니다. 챗봇 테스트에서 메시지를 보내면 바로 반영됩니다."/>:data?page==="overview"?<Overview d={data}/>:page==="intent"?<IntentPage d={data}/>:page==="api"?<ApiPage d={data}/>:page==="refusal"?<RefusalPage d={data}/>:<Conversations d={data}/>:null}</main></div>}
