"use client";
import { useCallback, useEffect, useState } from "react";
type Data={coverage:{logs:number;api:number;latency:number;tokens:number;tools:number};summary:{messages:number;conversations:number;responseRate:number|null;refusalRate:number|null;apiSuccessRate:number|null;averageLatencyMs:number|null;inputTokens:number;outputTokens:number;estimatedCostUsd:number|null};daily:{date:string;messages:number}[];intents:{name:string;count:number;share:number}[];tools:{name:string;calls:number;successRate:number|null;averageLatencyMs:number|null}[]};
const nf=new Intl.NumberFormat("ko-KR");const pct=(v:number|null)=>v===null?"측정 전":`${v.toFixed(1)}%`;const time=(v:number|null)=>v===null?"측정 전":v>=1000?`${(v/1000).toFixed(1)}초`:`${v}ms`;
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="analytics-card analytics-kpi"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Head({title,sub}:{title:string;sub:string}){return <div className="analytics-section-head"><div><h3>{title}</h3><p>{sub}</p></div></div>}
function Empty({text}:{text:string}){return <div className="analytics-empty"><span>⌁</span><strong>아직 표시할 데이터가 없어요</strong><p>{text}</p></div>}
/* The request callback owns the dashboard's remote-data state updates. */
// eslint-disable-next-line react-hooks/set-state-in-effect
export default function BotAnalyticsDashboard({botId,botName}:{botId:string;botName:string}){const[days,setDays]=useState(30);const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{try{const r=await fetch(`/api/analytics?days=${days}&botId=${encodeURIComponent(botId)}`,{cache:"no-store"});if(!r.ok)throw new Error("분석 데이터를 불러오지 못했습니다.");setData(await r.json());setError("")}catch(e){setError(e instanceof Error?e.message:"오류가 발생했습니다.")}},[botId,days]);useEffect(()=>{void load()},[load]);if(error)return <div className="analytics-error"><strong>데이터를 불러오지 못했어요</strong><p>{error}</p><button onClick={()=>void load()}>다시 시도</button></div>;if(!data)return <div className="analytics-loading"><i/><p>{botName} 데이터를 집계하고 있어요</p></div>;const max=Math.max(...data.intents.map(x=>x.count),1);return <div className="analytics-app qa-analytics"><main className="analytics-main"><div className="analytics-page-heading"><div><small><i/>해당 챗봇 실제 데이터</small><h1>{botName} 분석</h1><p>이 챗봇에서 발생한 대화와 AI 응답 품질만 모아봅니다.</p></div><div className="analytics-filters"><label><span>기간</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>최근 7일</option><option value={30}>최근 30일</option><option value={90}>최근 90일</option></select></label><button onClick={()=>void load()}>↻ 새로고침</button></div></div><div className="analytics-kpi-grid"><Kpi label="대화 세션" value={`${nf.format(data.summary.conversations)}개`} note={`${data.summary.messages}개 메시지`}/><Kpi label="응답 완료율" value={pct(data.summary.responseRate)} note="거절 응답 제외"/><Kpi label="거절률" value={pct(data.summary.refusalRate)} note="답변 불가 감지"/><Kpi label="API 성공률" value={pct(data.summary.apiSuccessRate)} note={`${data.coverage.api}건 측정`}/><Kpi label="평균 응답 시간" value={time(data.summary.averageLatencyMs)} note={`${data.coverage.latency}건 측정`}/><Kpi label="사용 토큰" value={nf.format(data.summary.inputTokens+data.summary.outputTokens)} note={`${data.coverage.tokens}건 측정`}/></div>{data.coverage.logs===0?<Empty text="테스트 화면이나 설치된 위젯에서 대화하면 이곳에 바로 집계됩니다."/>:<div className="analytics-grid-two"><section className="analytics-card analytics-section-card"><Head title="문의 의도" sub="이 챗봇에 들어온 질문 유형"/>{data.intents.slice(0,8).map(x=><div className="analytics-bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${(x.count/max)*100}%`}}/></div><b>{x.count}건</b></div>)}</section><section className="analytics-card analytics-section-card"><Head title="도구 성능" sub="문서 검색 등 실제 실행 결과"/>{data.tools.length?<table className="analytics-table"><thead><tr><th>도구</th><th>호출</th><th>성공률</th></tr></thead><tbody>{data.tools.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td>{x.calls}건</td><td>{pct(x.successRate)}</td></tr>)}</tbody></table>:<Empty text="측정된 도구 실행이 없습니다."/>}</section></div>}</main></div>}
