"use client";

import { useCallback, useEffect, useState } from "react";

type Handoff = { id:string; session_id:string; status:string; reason:string|null; bot_name:string; customer_name:string|null; assigned_agent_name:string|null; updated_at:number; last_message:string|null; telegram_topic_id:number|null };
type Message = { id:string; sender_type:string; sender_name:string|null; content:string; created_at:number };

export default function SupportPage() {
  const [items,setItems]=useState<Handoff[]>([]); const [selected,setSelected]=useState<Handoff|null>(null);
  const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/support/handoffs",{cache:"no-store"});if(r.ok)setItems(await r.json())},[]);
  const loadMessages=useCallback(async(id:string)=>{const r=await fetch(`/api/support/handoffs?sessionId=${encodeURIComponent(id)}`,{cache:"no-store"});if(r.ok)setMessages(await r.json())},[]);
  useEffect(()=>{void load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
  useEffect(()=>{if(!selected)return;void loadMessages(selected.session_id);const timer=setInterval(()=>loadMessages(selected.session_id),2500);return()=>clearInterval(timer)},[selected,loadMessages]);
  async function action(name:"accept"|"close"){if(!selected)return;await fetch("/api/support/handoffs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:selected.session_id,action:name})});await load();await loadMessages(selected.session_id)}
  async function send(){if(!selected||!text.trim())return;await fetch("/api/support/handoffs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:selected.session_id,message:text})});setText("");await loadMessages(selected.session_id)}
  const labels:{[key:string]:string}={waiting:"대기 중",active:"상담 중",closed:"종료"};
  return <div className="max-w-6xl"><div className="mb-6"><p className="text-xs font-semibold text-violet-600">HUMAN SUPPORT</p><h1 className="text-2xl font-bold text-gray-900 mt-1">상담원 연결 관리</h1><p className="text-sm text-gray-500 mt-1">Q&A·AI 챗봇에서 이관된 고객 상담을 확인합니다.</p></div>
    <div className="grid grid-cols-[360px_1fr] gap-4 min-h-[650px]">
      <section className="bg-white border border-gray-200 rounded-xl overflow-hidden"><div className="p-4 border-b font-semibold text-sm">상담 요청 {items.length}건</div>{items.length?items.map(item=><button key={item.id} onClick={()=>setSelected(item)} className={`w-full text-left p-4 border-b hover:bg-violet-50 ${selected?.id===item.id?"bg-violet-50":""}`}><div className="flex justify-between gap-2"><b className="text-sm text-gray-900">{item.customer_name||"고객"}</b><span className={`text-xs ${item.status==="waiting"?"text-amber-600":item.status==="active"?"text-green-600":"text-gray-400"}`}>{labels[item.status]||item.status}</span></div><p className="text-xs text-gray-500 mt-1">{item.bot_name} · {item.reason||"상담 요청"}</p><p className="text-xs text-gray-400 mt-2 truncate">{item.last_message}</p></button>):<p className="p-8 text-center text-sm text-gray-400">접수된 상담이 없습니다.</p>}</section>
      <section className="bg-white border border-gray-200 rounded-xl flex flex-col overflow-hidden">{selected?<><header className="p-4 border-b flex items-center justify-between"><div><b className="text-sm">세션 {selected.session_id.slice(0,8)}</b><p className="text-xs text-gray-500 mt-1">{selected.telegram_topic_id?`Telegram Topic #${selected.telegram_topic_id}`:"로컬 상담 대기열"}</p></div><div className="flex gap-2">{selected.status==="waiting"&&<button onClick={()=>action("accept")} className="px-3 py-2 rounded-lg bg-violet-600 text-white text-xs">상담 시작</button>}{selected.status!=="closed"&&<button onClick={()=>action("close")} className="px-3 py-2 rounded-lg border border-red-200 text-red-600 text-xs">상담 종료</button>}</div></header><div className="flex-1 overflow-y-auto p-5 space-y-3 bg-gray-50">{messages.map(m=><div key={m.id} className={`max-w-[75%] rounded-xl px-4 py-3 text-sm ${m.sender_type==="customer"?"ml-auto bg-violet-600 text-white":m.sender_type==="agent"?"bg-blue-50 text-blue-900":"bg-white border border-gray-200 text-gray-700"}`}><p>{m.content}</p><small className="block mt-1 opacity-60">{m.sender_name||({customer:"고객",agent:"상담원",bot:"챗봇",system:"시스템"}[m.sender_type])}</small></div>)}</div>{selected.status!=="closed"&&<div className="p-4 border-t flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder="고객에게 답변 입력..." className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm"/><button onClick={send} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm">전송</button></div>}</>:<div className="m-auto text-center text-gray-400"><div className="text-4xl mb-3">🎧</div><p className="text-sm">왼쪽에서 상담을 선택하세요.</p></div>}</section>
    </div></div>;
}
